apiVersion: neotoma v2.0
headers: 2
kind: Development
metadata:
- column: datasetname
  neotoma: ndb.datasets.datasetname
  notes: null
  overwrite: false
  required: true
  value: null
- column: datasettypeid
  neotoma: ndb.datasettypes.datasettype
  notes: null
  overwrite: false
  required: true
  value: ostracode surface sample
- column: databaseid
  neotoma: ndb.datasetdatabases.databasename
  notes: null
  overwrite: false
  required: true
  value: East Asian Nonmarine Ostracod Database
- column: labnumber
  neotoma: ndb.samples.labnumber
  notes: null
  overwrite: false
  required: false
  value: null
- column: variableelement
  neotoma: ndb.variableelements.variableelementid
  notes: null
  overwrite: false
  required: true
  value: Valve
- column: Handle
  neotoma: ndb.collectionunits.handle
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Original sample number
  neotoma: ndb.datasets.notes
  notes: 'Original Sample Number:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Sample Analyst
  neotoma: ndb.sampleanalysts.contactid
  overwrite: false
  required: false
  rowwise: true
  type: string
  vocab: [fixed]
- column: Site name
  neotoma: ndb.sites.sitename
  notes: If empty, use waterBody
  overwrite: false
  required: true
  rowwise: false
  type: string
- column: basisOfRecord
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: bibliographicCitation
  formatorrange: ^10.\d{4,9}/[-._;()/:A-Z0-9]+$
  neotoma: ndb.publications.id
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: comments*
  neotoma: ndb.sites.notes
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: conductivity*
  neotoma: ndb.datasets.notes
  notes: 'Conductivity:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: continent
  neotoma: "\u2014NA\u2014"
  notes: This is a spatial overlay
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: country
  neotoma: ndb.geopoliticalunits.geopoliticalunit
  overwrite: true
  required: true
  rowwise: true
  type: string
- column: day
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: decimalLatitude
  neotoma: ndb.sites.geog.latitude
  overwrite: false
  required: true
  rowwise: false
  type: float
- column: decimalLongitude
  neotoma: ndb.sites.geog.longitude
  overwrite: false
  required: true
  rowwise: false
  type: float
- column: dissolved oxygen*
  neotoma: ndb.datasets.notes
  notes: 'Dissolved Oxygen:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: duration*
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: environment*
  neotoma: "\u2014NA\u2014"
  notes: This is a modifier to the depositional environment and might be "location
    within unit"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: eventDate
  formatorrange: '%Y-%m-%d'
  neotoma: ndb.collectionunits.colldate
  overwrite: false
  required: false
  rowwise: false
  type: date
- column: eventDate
  formatorrange: '%Y-%m-%d'
  neotoma: ndb.sampleages.age
  overwrite: false
  required: false
  rowwise: false
  type: date
- column: family
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: females
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: genus
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: geodeticDatum
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: true
  rowwise: false
  type: string
- column: habitat
  neotoma: ndb.depenvttypes.depenvt
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: island
  neotoma: "\u2014NA\u2014"
  notes: This is spatial overlay (except when it isn't)
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: islandGroup
  neotoma: "\u2014NA\u2014"
  notes: This is spatial overlay (except when it isn't)
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: lifeStage
  neotoma: "\u2014NA\u2014"
  notes: This must be some part of the data value/variable description, but I'm not
    sure where it is.
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: locality
  neotoma: ndb.geopoliticalunits.geopoliticalunit
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: males
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: males and females text
  neotoma: ndb.datasets.notes
  notes: 'Males & Females:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: month
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: municipality
  neotoma: ndb.geopoliticalunits.geopoliticalunit
  overwrite: true
  required: true
  rowwise: true
  type: string
- column: nameInPaper
  neotoma: ndb.datasets.notes
  notes: 'Name in paper:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: order
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: organismQuantity
  formatorrange: '> 0'
  neotoma: ndb.data.value
  overwrite: false
  required: false
  rowwise: true
  type: float
- column: pH*
  neotoma: ndb.datasets.notes
  notes: 'pH:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: recordedBy
  neotoma: ndb.datasetpis.contactid
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: Dataset Processor
  neotoma: ndb.datasetprocessor.contactid
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: salinity*
  neotoma: ndb.datasets.notes
  notes: 'Salinity:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: scientificName
  neotoma: ndb.data.values
  notes: This is a single Presence/absence value, we have to check to see if there's
    not information in this field
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: scientificNameAuthorship
  neotoma: ndb.taxa.publication
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: sex
  neotoma: "\u2014NA\u2014"
  notes: This must be some part of the data value/variable description, but I'm not
    sure where it is.
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: sexRatio*
  neotoma: "\u2014NA\u2014"
  notes: This must be some part of the data value/variable description, but I'm not
    sure where it is.
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: specificEpithet
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: stateProvince
  neotoma: ndb.geopoliticalunits.geopoliticalunit
  overwrite: true
  required: true
  rowwise: true
  type: string
- column: subfamily*
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: substrate*
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: superfamily*
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: temperature*
  neotoma: ndb.datasets.notes
  notes: 'Temperature:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: typeLocality*
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: vegetation*
  neotoma: ndb.datasets.notes
  notes: 'Vegetation:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: verbatimDepth
  neotoma: "\u2014NA\u2014"
  notes: This is sampling depth, not lake depth
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: verbatimElevation
  neotoma: ndb.sites.altitude
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: verbatimLocality
  neotoma: ndb.sites.sitedescription
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: waterBody
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: year
  neotoma: "\u2014NA\u2014"
  notes: This gets pasted together in the column eventDate
  overwrite: false
  required: false
  rowwise: false
  type: string
