apiVersion: neotoma v2.0
headers: 2
kind: Development
metadata:
- column: handleComplete
  neotoma: ndb.datasets.datasetname
  notes: null
  overwrite: false
  required: true
  rowwise: false
  value: null
- column: datasettypeid
  neotoma: ndb.datasettypes.datasettype
  notes: null
  overwrite: false
  required: true
  value: ostracode surface sample
- column: CollectionType
  neotoma: ndb.collectionunits.colltypeid
  notes: null
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: databaseid
  neotoma: ndb.datasetdatabases.databasename
  notes: null
  overwrite: false
  required: true
  value: East Asian Nonmarine Ostracod Database
- column: labnumber
  neotoma: ndb.samples.labnumber
  notes: null
  overwrite: false
  required: false
  value: null
- column: variableelement
  neotoma: ndb.variableelements.variableelement
  notes: null
  overwrite: false
  required: true
  rowwise: true
  type: string
- column: context
  neotoma: ndb.variables.variablecontext
  notes: null
  overwrite: false
  required: true
  rowwise: true
  type: string
- column: Handle
  neotoma: ndb.collectionunits.handle
  overwrite: true
  required: false
  rowwise: false
  type: string
- column: handleComplete
  neotoma: ndb.collectionunits.collunitname
  overwrite: true
  required: false
  rowwise: false
  type: string
- column: handleComplete
  neotoma: ndb.analysisunits.analysisunitname
  overwrite: true
  required: false
  rowwise: false
  type: string
- column: handleComplete
  neotoma: ndb.samples.samplename
  overwrite: true
  required: false
  rowwise: false
  type: string
- column: Original sample number
  neotoma: ndb.datasets.notes
  notes: 'Original Sample Number:'
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Name In Publication
  neotoma: ndb.datasets.notes
  notes: 'Name in paper:'
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: males and females text
  neotoma: ndb.datasets.notes
  notes: null
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: pH
  neotoma: ndb.datasets.notes
  notes: 'pH:'
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: conductivity
  neotoma: ndb.datasets.notes
  notes: 'Conductivity:'
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: temperature
  neotoma: ndb.datasets.notes
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: dissolved oxygen
  neotoma: ndb.datasets.notes
  notes: 'Dissolved Oxygen:'
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: salinity
  neotoma: ndb.datasets.notes
  notes: 'Salinity:'
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: vegetation
  neotoma: ndb.datasets.notes
  notes: 'Vegetation:'
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Sample Analyst
  neotoma: ndb.sampleanalysts.contactname
  overwrite: false
  required: false
  rowwise: true
  type: string
  vocab: [fixed]
- column: Site name
  neotoma: ndb.sites.sitename
  notes: If empty, use waterBody
  overwrite: false
  required: true
  rowwise: false
  type: string
- column: basisOfRecord
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: bibliographicCitation
  formatorrange: citation
  neotoma: ndb.publications.citation
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: comments
  neotoma: ndb.sites.notes
  overwrite: false
  required: false
  rowwise: true
  type: string

- column: continent
  neotoma: "\u2014NA\u2014"
  notes: This is a spatial overlay
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: day
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: decimalLatitude
  neotoma: ndb.sites.geog.latitude
  overwrite: false
  required: true
  rowwise: false
  type: float
- column: decimalLongitude
  neotoma: ndb.sites.geog.longitude
  overwrite: false
  required: true
  rowwise: false
  type: float

- column: duration
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: environment
  neotoma: "\u2014NA\u2014"
  notes: This is a modifier to the depositional environment and might be "location
    within unit"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: eventDate
  formatorrange: '%Y-%m-%d'
  neotoma: ndb.collectionunits.colldate
  overwrite: false
  required: false
  rowwise: false
  type: date
- column: eventDate
  formatorrange: '%Y-%m-%d'
  neotoma: ndb.chronologies.age
  overwrite: false
  required: false
  rowwise: false
  type: date
- column: Age Model
  formatorrange: '%Y-%m-%d'
  neotoma: ndb.chronologies.agemodel
  overwrite: false
  required: false
  rowwise: false
  type: str
- column: Age Type
  formatorrange: '%Y-%m-%d'
  neotoma: ndb.chronologies.agetype
  overwrite: false
  required: false
  rowwise: false
  type: str
- column: eventDate
  formatorrange: '%Y-%m-%d'
  neotoma: ndb.sampleages.age
  overwrite: false
  required: false
  rowwise: false
  type: date
- column: family
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: value
  neotoma: ndb.data.value
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: variableelement
  neotoma: ndb.variables.variableelement
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: count
  neotoma: ndb.variables.variableunits
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Taxonname
  neotoma: ndb.variables.taxon
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: geodeticDatum
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: true
  rowwise: false
  type: string
- column: habitat
  neotoma: ndb.collectionunits.depenvtid
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: island
  neotoma: "\u2014NA\u2014"
  notes: This is spatial overlay (except when it isn't)
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: islandGroup
  neotoma: "\u2014NA\u2014"
  notes: This is spatial overlay (except when it isn't)
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: lifeStage
  neotoma: "\u2014NA\u2014"
  notes: This must be some part of the data value/variable description, but I'm not
    sure where it is.
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: country
  neotoma: ndb.sitegeopolitical.geopoliticalunit1
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: stateProvince
  neotoma: ndb.sitegeopolitical.geopoliticalunit2
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: municipality
  neotoma: ndb.sitegeopolitical.geopoliticalunit3
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: locality
  neotoma: ndb.sitegeopolitical.geopoliticalunit4
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: month
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: order
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: recordedBy
  neotoma: ndb.datasetpis.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: recordedBy
  neotoma: ndb.collectors.contactname
  overwrite: false
  required: false
  rowwise: true
  type: string
  vocab: [fixed]
- column: Dataset Processor
  neotoma: ndb.datasetprocessor.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]

- column: scientificNameAuthorship
  neotoma: ndb.taxa.publication
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: sex
  neotoma: "\u2014NA\u2014"
  notes: This must be some part of the data value/variable description, but I'm not
    sure where it is.
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: sexRatio
  neotoma: "\u2014NA\u2014"
  notes: This must be some part of the data value/variable description, but I'm not
    sure where it is.
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: specificEpithet
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: subfamily
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: substrate
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: superfamily
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: typeLocality
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: true
  type: string

- column: verbatimDepth
  neotoma: "\u2014NA\u2014"
  notes: This is sampling depth, not lake depth
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: verbatimElevation
  neotoma: ndb.sites.altitude
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: verbatimLocality
  neotoma: ndb.sites.sitedescription
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: waterBody
  neotoma: "\u2014NA\u2014"
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: year
  neotoma: "\u2014NA\u2014"
  notes: This gets pasted together in the column eventDate
  overwrite: false
  required: false
  rowwise: false
  type: string
