apiVersion: neotoma v2.0
headers: 2
kind: Development
metadata:
- column: Sitename
  neotoma: ndb.sites.sitename
  overwrite: false
  required: true
  rowwise: false
  type: string
- column: SiteNotes
  neotoma: ndb.sites.notes
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Latitude
  neotoma: ndb.sites.geog.latitude
  notes: Create from CSV file unite LATDEG, LATMIN, LATSEC
  overwrite: false
  required: true
  rowwise: false
  type: float
- column: Longitude
  neotoma: ndb.sites.geog.longitude
  notes: Create from CSV file unite LONGDEG, LONMIN, LONSEC
  overwrite: false
  required: true
  rowwise: false
  type: float
- column: Country
  neotoma: ndb.sitegeopolitical.geopoliticalunit1
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: Region
  neotoma: ndb.sitegeopolitical.geopoliticalunit2
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: Handle
  neotoma: ndb.collectionunits.collunitname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Handle
  neotoma: ndb.collectionunits.handle
  overwrite: true
  required: false
  rowwise: false
  type: string
- column: collection_type
  neotoma: ndb.collectionunits.colltypeid
  notes: null
  overwrite: false
  required: false
  value: modern
- column: Handle
  neotoma: ndb.datasets.datasetname
  notes: null
  overwrite: false
  required: true
  value: null
- column: DatasetNotes
  neotoma: ndb.datasets.notes
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: datasettypeid
  neotoma: ndb.datasettypes.datasettype
  notes: null
  overwrite: false
  required: true
  value: ostracode surface sample
- column: databaseid
  neotoma: ndb.datasetdatabases.databasename
  notes: null
  overwrite: false
  required: true
  value: Nonmarine Ostracod Distribution in Europe Database
- column: Taxonname
  neotoma: ndb.variables.taxon
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: variableelement
  neotoma: ndb.variables.variableelement
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: context
  neotoma: ndb.variables.variablecontext
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: value
  neotoma: ndb.data.value
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: count
  neotoma: ndb.variables.variableunits
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: PI
  neotoma: ndb.datasetpis.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: PI
  neotoma: ndb.collectors.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: DatasetProcessor 
  neotoma: ndb.datasetprocessor.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: SampleAnalyst
  neotoma: ndb.sampleanalysts.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
  vocab: [fixed]
- column: Reference
  neotoma: ndb.publications.citation
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: CollectionUnitNotes
  neotoma: ndb.collectionunits.notes
  overwrite: false
  required: false
  rowwise: false
  type: string